"""add video transcript

Revision ID: 36e55952253c
Revises: 003_add_subtitle_styles
Create Date: 2026-07-12 14:03:10.504368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e55952253c'
down_revision = '003_add_subtitle_styles'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcript', sa.JSON(), nullable=True))
    op.alter_column('videos', 'source_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'source_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('videos', 'transcript')
    # ### end Alembic commands ###
