"""add user credits

Revision ID: b91f3d457d02
Revises: f696843282f1
Create Date: 2026-07-12 14:55:44.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91f3d457d02'
down_revision = 'f696843282f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits_balance', sa.Integer(), server_default='300', nullable=False))
    op.add_column('users', sa.Column('credits_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits_used')
    op.drop_column('users', 'credits_balance')
    # ### end Alembic commands ###
