"""add voiceover

Revision ID: f696843282f1
Revises: 36e55952253c
Create Date: 2026-07-12 14:29:27.947427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f696843282f1'
down_revision = '36e55952253c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('audio_mode', sa.String(length=32), server_default='subtitles_only', nullable=False))
    op.add_column('videos', sa.Column('voice', sa.String(length=32), server_default='alloy', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'voice')
    op.drop_column('videos', 'audio_mode')
    # ### end Alembic commands ###
